export const HIDE_MODAL = "HIDE_MODAL";
export const SHOW_MODAL = "SHOW_MODAL";
export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const SHOW_FEEDBACK = "SHOW_FEEDBACK";
export const HIDE_FEEDBACK = "HIDE_FEEDBACK";
export const FETCH_PRODUCTS_FROM_CACHE_SUCCESS =
  "FETCH_PRODUCTS_FROM_CACHE_SUCCESS";
export const FETCH_PRODUCTS_FROM_NETWORK_SUCCESS =
  "FETCH_PRODUCTS_FROM_NETWORK_SUCCESS";
