export const HIDE_MODAL = "HIDE_MODAL";
export const SHOW_MODAL = "SHOW_MODAL";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const FETCH_PRODUCTS_FROM_CACHE_SUCCESS =
  "FETCH_PRODUCTS_FROM_CACHE_SUCCESS";
export const SHOW_EDIT_PRODUCT_MODAL = "SHOW_EDIT_PRODUCT_MODAL";
export const SHOW_DELETE_PRODUCT_MODAL = "SHOW_DELETE_PRODUCT_MODAL";
export const FETCH_PRODUCTS_FROM_NETWORK_SUCCESS =
  "FETCH_PRODUCTS_FROM_NETWORK_SUCCESS";
export const FETCH_PRODUCTS_FROM_NETWORK_FAILED =
  "FETCH_PRODUCTS_FROM_NETWORK_FAILED";
export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";
